site_name: Guide ISIA U
site_url: https://guide.isiaurbino.net
copyright: Copyright &copy; 2025 - ISIA Urbino
nav:
  - Home: index.md
  - Ammissioni:
      - 'Ammissioni': 'ammissioni/index.md'
  - Immatricolazioni:
      - 'Immatricolazioni': 'immatricolazioni/index.md'
  - Iscrizione agli anni successivi:
      - 'Iscrizione agli anni successivi': 'iscrizione-anni-successivi/index.md'
      - 'Iscrizione ordinaria a settembre': 'iscrizione-anni-successivi/iscrizione-ordinaria-settembre.md'
      - 'Iscrizione non diplomati': 'iscrizione-anni-successivi/iscrizione-non-diplomati.md'
      - 'Tutti gli allegati': 'iscrizione-anni-successivi/tutti-gli-allegati.md'
  - Piano di studi:
      - 'Piano di studi': 'piano-di-studi/index.md'
  - Calendari delle lezioni:
      - 'Calendari delle lezioni': 'calendari-lezioni/index.md'
      - 'Aggiungi al Calendario Google': 'calendari-lezioni/aggiungi-al-Google-Calendar.md'
      - 'Abilita le notifiche': 'calendari-lezioni/abilita-le-notifiche.md'
  - Frequenza alle lezioni:
      - 'Frequenza alle lezioni': 'frequenza-lezioni/index.md'
  - Crediti liberi:
      - 'Crediti liberi': 'crediti-liberi/index.md'
      - 'Tirocini': 'crediti-liberi/tirocini.md'
  - Tesi:
      - 'Presentazione domanda di tesi': 'presentazione-domanda-di-tesi/index.md'
      - 'Come presentare la domanda di tesi': 'presentazione-domanda-di-tesi/presentazione-domanda-di-tesi.md'
  - Tasse e contributi:
      - 'Tasse e contributi': 'tasse-e-contributi/index.md'
      - 'Agevolazioni ISEE': 'tasse-e-contributi/agevolazioni-ISEE.md'
      - 'Borsa di studio ERDIS': 'tasse-e-contributi/borsa-di-studio-ERDIS.md'
      - 'Tassa regionale ERDIS': 'tasse-e-contributi/tassa-regionale-ERDIS-il-diritto-allo-studio.md'
      - 'Rata agevolata': 'tasse-e-contributi/rata-agevolata.md'
      - 'Contributo onnicomprensivo annuale di funzionamento': 'tasse-e-contributi/contributo-onnicomprensivo-annuale-funzionamento.md'
      - 'PagoPA': 'tasse-e-contributi/PagoPA.md'
  - Certificati:
      - 'Certificati': 'certificati/index.md'
  - Modulistica:
      - 'Modulistica': 'modulistica/index.md'
  - Regolamenti:
      - 'Regolamenti': 'regolamenti/index.md'

theme:
  name: material
  language: it
  logo: assets/ISIAU_logo-light.png
  favicon: assets/favicon.png
  features:
    - #navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.indexes
    - #navigation.prune
    - #navigation.expand
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/brightness-3
        name: Modalità notte
     # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-7
        name: Modalità giorno
extra:
  generator: false
  analytics:
    provider: google
    property: G-CQ6908H944
    feedback:
      title: Questa pagina ti è stata utile?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Sì, mi è stata utile
          data: 1
          note: >-
            Grazie per il tuo feedback, ci aiuterà a migliorare!
        - icon: material/emoticon-sad-outline
          name: Ci sono margini di miglioramento
          data: 0
          note: >- 
            Grazie per il tuo feedback! Aiutaci a migliorare questa pagina scrivendo <a href="mailto:guide@isiaurbino.net" rel="noopener">alla nostra email</a>.
  consent:
    title: Cookie consent
    description: >- 
      Questo sito non esegue alcun tipo di profilazione, né richiede alcun dato personale. I suoi cookie hanno il solo scopo di aggiornare il conteggio visiste e, se possibile, ripristinare le vostre preferenze di lettura.     
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - javascripts/extra.js
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
